#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee -a /var/www/html/index.nginx-debian.html
sudo service nginx restart
