#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
