#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt install -y nginx

# index.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html

# redirect 301
sudo sed -i '36a rewrite ^/redirect_me https://youtu.be/MzlSVFtxb4c permanent;' /etc/nginx/sites-available/default

# 404 Error Page
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/error_404.html
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
