#!/usr/bin/env bash
# Install haproxy and configure 2 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend abracodea-frontend
    bind *:80
    default_backend abracodea-backend
backend abracodea-backend
    balance roundrobin
    server 1378-web-01 3.236.102.171:80 check
    server 1378-web-02 35.174.62.188:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
