#!/usr/bin/env bash
# Install haproxy and configure your 2 servers 1378-web-01 & 1378-web-02
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get -y install haproxy


sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 1378-web-01 3.236.102.171 check\n\tserver 1378-web-02 35.174.62.188 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy start
