#!/usr/bin/env bash
# Installs and configures HAproxy on your lb-01 server.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 1378-web-01 34.74.212.27:80 check\n\tserver 1378-web-02 3.236.108.103:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
