#!/usr/bin/env bash
# Backup databases and create a compressed archive out of it

# variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
