#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
while ((i < 10))
do
    echo "Best School"
    let i++
    if ((i == 9))
    then
        echo "Hi"
    fi
done
