#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
while ((i < 10))
do
    let i++
    if ((i == 4))
    then
        echo "bad luck"
    elif ((i == 8))
    then
	echo "good luck"
    else
	echo "Best School"
    fi
done
