#!/usr/bin/env bash
# script that displays all active IPv4 IPs on the machines executed onit

# saving all the ip addresses
ip_addresses=$(hostname -I)

# splitting them by space
ip_addresses=(${ip_addresses//" "/ })

# Print each ip address line by line
for ip in "${ip_addresses[@]}";
do
  printf "$ip\n"
done
