#!/usr/bin/env bash
# Fixes the issues with task #1 to make it shorter
chmod 644 /etc/nginx/nginx.conf
sudo sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
